-- Melanalandhula v5: compatible with the Supabase setup already created.
-- Existing table: public.announcements(title, content, image_url, created_at)
-- Existing bucket: Gallery (public)

create table if not exists public.gallery (
  id bigint generated by default as identity primary key,
  title text not null default 'Melanalandhula',
  url text not null,
  storage_path text not null,
  created_at timestamptz not null default now()
);

alter table public.gallery enable row level security;

drop policy if exists "public can read gallery" on public.gallery;
create policy "public can read gallery"
on public.gallery for select
using (true);

drop policy if exists "authenticated can insert gallery" on public.gallery;
create policy "authenticated can insert gallery"
on public.gallery for insert to authenticated
with check (true);

drop policy if exists "authenticated can update gallery" on public.gallery;
create policy "authenticated can update gallery"
on public.gallery for update to authenticated
using (true) with check (true);

drop policy if exists "authenticated can delete gallery" on public.gallery;
create policy "authenticated can delete gallery"
on public.gallery for delete to authenticated
using (true);

-- Storage write policies for the existing Gallery bucket.
drop policy if exists "Authenticated users can upload gallery files" on storage.objects;
create policy "Authenticated users can upload gallery files"
on storage.objects for insert to authenticated
with check (bucket_id = 'Gallery');

drop policy if exists "Authenticated users can update gallery files" on storage.objects;
create policy "Authenticated users can update gallery files"
on storage.objects for update to authenticated
using (bucket_id = 'Gallery')
with check (bucket_id = 'Gallery');

drop policy if exists "Authenticated users can delete gallery files" on storage.objects;
create policy "Authenticated users can delete gallery files"
on storage.objects for delete to authenticated
using (bucket_id = 'Gallery');

-- The Gallery bucket is public, so its image URLs can be viewed by visitors.
